# Site settings
title: undefined.kr Blog
email: undefinedkr@gmail.com
description: "undefined.kr blog, 언디파인드 블로그. 모임 공지사항과 기술, 정보를 공유하기 위한 블로그."
baseurl: ""
url: "http://blog.undefined.kr"
# twitter_username: jekyllrb
github_username:  undefined-kr

# Build settings
markdown: kramdown
permalink: pretty
